### ISSUE TITLE
SOW: Decide Upgrade Path

### ISSUE THREAD

**Issue by aprilrieger** [scientist-softserv/archives_online#1]
## Summary
[SOW](https://docs.google.com/document/d/1f0aP5ZDUTj0S9RBN0jeDXT5nAYapszEdyG3wntO1FlI/edit)

> SoftServ will spend approximately two days investigating the best path between two approaches:  upgrading the current IU application or deploying a new ArcLight and bringing in customizations.  A new instance would allow the implementation of some best-practices and cleaner code for customizations, however IU would like to evaluate cost/benefit against the effort of upgrading the current application.

We are planning to use the 12 additional senior hours on this initial investigation. Once we have our recommendation, we need to get feedback from IU's team in the s3-indiana-arclight-client channel

## Acceptance Criteria
- [ ] Recommendation is sent to Randall, Jim, Bri, and Julie in the s3-indiana-arclight-client channel
- [ ] A path to move forward with is decided upon

**Comment by ShanaLMoore** [comment]
recommendations sent to client this morning: https://assaydepot.slack.com/files/U03JT0HHTA7/F07JKAJ2N48/upgrading_ngao_or_continuing_with_archives_online.pdf

[slack](https://assaydepot.slack.com/archives/C07GJGVQS2V/p1724251942121899)
