### ISSUE TITLE
EAD implementation

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/archives_online#13]
# Summary

~Port over ngao's implementation of EAD~

UPDATE: Most of the EAD implementation we see in ngao is related to the admin interface. The client does not want to port this over after all. 

## TASKS: 

1. Get sample EADs from the client
2. Import them in staging
3. Have the client review and provide feedback for any changes we need to make
4. Or, the client can provide screenshots of how they expect the EADs to look after import

# Acceptance Criteria

- [x] The clients will review imported sample EADs
- [x] Create separate tickets if there are any changes we need to make. 

# Notes

Original EAD [implementations: 
- [PR](https://github.com/IUBLibTech/ngao/pull/29) for processing
- https://github.com/IUBLibTech/ngao/commit/75fcb2facd124b46196d47a5f27f0126405a1962 commit 
  - #47 
  - #48 

## Sample Files

ref: [SLACK](https://assaydepot.slack.com/archives/C07GJGVQS2V/p1724360995069889)

**Comment by ShanaLMoore** [comment]
```
DIR=data REPOSITORY_ID=iupuigeneral rake arclight:index_dir
```

**Comment by ShanaLMoore** [comment]
Kirk imported the sample EADs in staging. 

TODO: The client needs to review and provide feedback.

**Comment by brijmcla** [comment]
All note types display at the item and collection level are displaying with the exception of bibliography notes.

**Comment by brijmcla** [comment]
`unitid` is not displaying at the item level. 
Here is the EAD for the item in the following example: 
```
 <c03 id="aspace_VAD4090-00094" level="item">
            <did>
              <unittitle>Choices</unittitle>
              <unitid>COL 5 VH 1</unitid>
              <unitid audience="internal" identifier="COL 5 VH 1" type="shelf">COL 5 VH 1</unitid>
              <unitid audience="internal" identifier="1" type="collector">1</unitid>
              <origination label="Creator"><persname source="ingest">Sampson,
                Sheldon</persname></origination>
              <unitdate datechar="creation" normal="1993/1993">1993</unitdate>
              <physdesc id="aspace_f442258bcd8b6f91bff824ed586b90b6" label="Physical Description">1
                videocassette (VHS)</physdesc>
            </did>
            <originalsloc id="aspace_cbf65fde88732d9455afab810a03f9db">
              <head>Format of original version</head>
              <p>1 film reel (28 minutes) : sound, color ; 16 mm</p>
            </originalsloc>
          </c03>
```
In the staging environment, you can see the collection level `unitid` if you click the More Info button on the top left corner of the screen (see screenshot). 
![no_unit_ids](https://github.com/user-attachments/assets/f368a978-8741-4d9c-ba42-642c40d2bcd2)

In our production environment, all `unitid` display under the field "Component Identifier." COL 5 VH 1 and 1 are the two `unitid` in this example.
![unitids_arclight_prod](https://github.com/user-attachments/assets/57451bd0-a9b1-48ba-95fe-3b33f40abc52)


Caveats: We have an error right now in our production environment where the first unitid is duplicated. There are also no labels for the field beyond "component identifier."

**Comment by brijmcla** [comment]
`unittitle` attribute text formatting is not coming through. However, this is an issue we have on our production arclight instance as well. 

For example
```
      <c01 id="aspace_VAD9218-00001" level="series">
        <did>
          <unittitle><title render="bold">Media</title></unittitle>
          <unitdate datechar="creation" normal="1959/2016" type="inclusive">1959-2016</unitdate>
        </did>
```
"Media, 1959-2016" should be bolded per the attribute rendering in EAD. In the following screenshot, you can see "Media, 1959-2016" at the title, in the breadcrumbs, and in the collection content sidebar. Text formatting does not come through in any location. 

![no_text_formatting](https://github.com/user-attachments/assets/900eb798-4ab0-41c4-a65d-27910ca42b84)

**Comment by brijmcla** [comment]
As far as I can tell, text formatting encoded as EAD attributes are all working with the exception of `unititle`, as explained in previous comment.

**Comment by brijmcla** [comment]
Note labels are not coming through. I think Arclight overrides them. We are experiencing this in our production instance, as well, so this is not a new issue. 
Here is the EAD for the following example:
```
        <c02 id="aspace_VAE0165-00002" level="item">
          <did>
            <unittitle>Adelaide Hall on stage</unittitle>
            <unitid audience="internal" identifier="PA005852" type="shelf">PA005852</unitid>
            <physdesc altrender="whole"><extent altrender="materialtype spaceoccupied">1
                Photograph</extent><extent altrender="carrier">black &amp; white ; 8.5 x 6.5
                in.</extent></physdesc>
            <unitdate calendar="gregorian" datechar="creation" era="ce" normal="1989/1989"
              >1989</unitdate>
            <container altrender="Document Storage Case (Letter - skinny)"
              id="aspace_b81104151380858a0db12f5d27a4e77c" label="box" type="box">1</container>
          </did>
          <altformavail id="aspace_6276c1f9a40d0276044eaf085424f856">
            <head>Online Access</head>
            <p><extref xlink:href="http://purl.dlib.indiana.edu/iudl/images/VAD5465/VAD5465-000107"
                >http://purl.dlib.indiana.edu/iudl/images/VAD5465/VAD5465-000107</extref></p>
          </altformavail>
          <odd id="aspace_9bec57e15b7cbd76428cd68e6325f6a2">
            <head>Shelf Number</head>
            <p>PA005852</p>
          </odd>
        </c02>
```
![note_labels](https://github.com/user-attachments/assets/3ab0655f-8679-48ae-b3c8-9689984f068b)

The `altformavail` note should have the label (`head`) "Online Access". The `odd` note should have the label (`head`) "Shelf Number". In our production instance, the labels aren't coming through, but we overrode the label for the odd `note` to be "General Note" instead of "Other descriptive data"
![note_labels_prod](https://github.com/user-attachments/assets/61188818-5d35-439f-a410-25fceddf35be)

To match our production instance, the only change would be overriding the label for `odd` to be "General note." I don't think that part is technically EAD implementation, though. Regardless, I wanted to identify that `head` isn't coming through.

**Comment by brijmcla** [comment]
Name and subject records came through successfully

**Comment by brijmcla** [comment]
Hierarchies within EAD came through successfully

**Comment by brijmcla** [comment]
Ordered lists within notes came through successfully (this was an issue before with arclight)

**Comment by brijmcla** [comment]
Besides what I commented as missing, I do not see any other missing EAD elements.

**Comment by kirkkwang** [comment]
Tickets were made and linked, closing this ticket.
