### ISSUE TITLE
:gift: Add Campus Features

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/archives_online#19]
# Summary

Ask clients for clarification, to fill in the details of this ticket.

# Acceptance Criteria

- [x] TODO: clarify acceptance criteria for campus features
- [x] Campus features include:
  - [x] campuses are indexed in solr and available for facets
  - [x] campuses are represented in the breadcrumbs
  - [x] #20 (<-- NOTE: campus cards on the homepage will be addressed in this ticket)

# Screenshots or Video

## Campus Cards

CAMPUS cards can be seen on the [homepage](https://archives.iu.edu/).
<details>

![Image](https://github.com/user-attachments/assets/f7ef04c6-afee-417b-befc-6e6283722166)

![image](https://github.com/user-attachments/assets/2df63232-ba7d-4699-8a35-3a84ece0e1f8)

</details>

## Facets
<details> 

![image](https://github.com/user-attachments/assets/98005c50-44a5-40ed-aee5-eece11d74beb)

</details> 

## Breadcrumbs

When you click on a card, the campus can be seen in the breadcrumbs. ie: 

<details> 

![Image](https://github.com/user-attachments/assets/fd9d8b2a-d2b2-44cf-b104-3c775dcd4a47)

![image (1)](https://github.com/user-attachments/assets/6974cd52-cc80-4a48-b686-07b351606758)

</details> 

# Testing Instructions

- [ ] Do a catalog search
- [ ] Confirm that the campus facet is showing
- [ ] Click into a collection
- [ ] Confirm that the campus breadcrumb is showing

# Notes

**Questions:** 
What is meant by "campus features?"

[PR](https://github.com/IUBLibTech/ngao/pull/17) that added the privacy policy to the ngao/production code

[PR](https://github.com/IUBLibTech/ngao/pull/14) for original campus cards implementation

**Comment by ShanaLMoore** [comment]
they want the campus/repository homepage. should be build in with breadcrumbs.

**Comment by ShanaLMoore** [comment]
ref accessibility review comment: https://github.com/scientist-softserv/archives_online/issues/31#issuecomment-2310580800

**Comment by kirkkwang** [comment]
✅ Passes QA

![Image](https://github.com/user-attachments/assets/10025e43-213c-4876-8608-ddff57beae31)

![Image](https://github.com/user-attachments/assets/37920839-ca7c-469c-b593-41c06a8d5fd8)

**Comment by brijmcla** [comment]
I'm confused about how campus information is indexing. When I do an empty search and facet by campus, all results are in the campus Indiana University Bloomington. However, all finding aids are within the IUPUI General Collections repository, which is under the campus IUPUI on the homepage. When I open a finding aid, the breadcrumbs display Indiana University>IUPUI General Collections>finding aid title. 
![campus](https://github.com/user-attachments/assets/f09d4dee-23d7-4bf2-a1f8-6f914f670f27)
![campus_facet](https://github.com/user-attachments/assets/5a2483b2-301b-4799-8230-04786585fc84)

**Comment by kirkkwang** [comment]
@brijmcla I reindexed, let me know if that looks better

**Comment by brijmcla** [comment]
It looks like the Repository search facet was removed at some point between when this ticket was created and now. Did it not play nicely with the Campus facet?

**Comment by kirkkwang** [comment]
@brijmcla that's a good catch, i brought a lot of the solr fields over and it didn't match well so I'll fix that.  Ex. `repository_sim` (from the old app) should now be `repository_ssim`.

**Comment by brijmcla** [comment]
Acceptance criteria has been met
