### ISSUE TITLE
:gift: Add Static Content Links to the Homepage Content

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/archives_online#20]
# Summary

IU has a custom homepage with static content links. The archives_online application should have the same. 

# Acceptance Criteria

- [x] Campus cards exist on the homepage and have show pages
- [x] Add footer
- [x] Add subfooter
- [x] The static links operate the same as those seen in production (not doing the admin link or admin content)
  - [x] add static content/pages in subfooter
    - [x] about
    - [x] contribute
    - [x] Harmful Language Statement (https://libraries.indiana.edu/harmful-language-statement) 
    - [x] **Do not include** Legacy Archives Online
- [x] Add Get Search Help below search bar 

# Screenshots or Video

<details>
<summary>See Screenshot</summary>

![Image](https://github.com/user-attachments/assets/a8b11f71-f115-4640-99d3-25d53e00de32)

</details>

# Testing Instructions

1. Visit softserve's [staging](https://archives-online-staging.notch8.cloud/)
2. This site should match the look and functionality of [production](https://archives.iu.edu/)'s homepage

- The user can click the `Get search help` link and be taken to the Help page.
- The footer exists on the home page with custom branding. 
- The user can click the `About` link and be taken to the About page.
- The user can click the `Contribute to AO` link and be taken to the Contribution page.

# Notes

maybe helpful: [Style Guide](https://www.iu.edu/brand/index.html)
production [code](https://github.com/IUBLibTech/ngao)

**Comment by kirkkwang** [comment]
✅ Passes QA

![Image](https://github.com/user-attachments/assets/be40fc74-d819-420a-8bb8-64d320219b87)

![Image](https://github.com/user-attachments/assets/93a35845-344f-4d9e-afd9-5b2860206880)

![Image](https://github.com/user-attachments/assets/c0528ddd-beda-42fe-959a-07f42c5f1077)

**Comment by brijmcla** [comment]
Acceptance criteria has been met.
