### ISSUE TITLE
:gift: Add Documentation for Advanced Search

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/archives_online#21]
# Summary

Ask clients for clarification to fill in the details of this ticket.

Dependent on 
- #20  

# Acceptance Criteria

- [ ] Adds Get search help link under the search bar
- [ ] that links you to a [documentation "help" page](https://archives.iu.edu/help). the /help route should be present in the application

# Screenshots or Video

![Image](https://github.com/user-attachments/assets/fa23aaac-627b-4c37-9a02-4d03f6a35182)

# Testing Instructions

# Notes

Maybe this ticket is referring to the documentation seen [here](https://archives.iu.edu/help)?

**Comment by sjproctor** [comment]
This ticket got combined with https://github.com/scientist-softserv/archives_online/issues/20
