### ISSUE TITLE
:gift: Remove History/Bookmarks

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/archives_online#22]
# Summary

Out-of-the-box Arclight comes with two unwanted features: 
- History
- Bookmarks

The task is to remove the features from the archives online application. 

# Acceptance Criteria

- [x] The ability to bookmark is absent from the archives online application
- [x]  The ability to search history is absent from the archives online application
- [x] **NOTE**: The users should also not be able to navigate to the corresponding urls, such as /bookmarks or /search_history, as a workaround for the links being absent in the header

# Screenshots or Video

### [Staging](https://archives-online-staging.notch8.cloud/)

<details>

<summary> See Screenshots </summary> 

These features can be seen in the header: 

![Image](https://github.com/user-attachments/assets/bd56de4c-39e4-475d-ac52-2f858d39289c)

#### bookmarks pages

![Image](https://github.com/user-attachments/assets/bbf8bb64-ad0c-4e87-8aab-0effa71dc162)

#### history page

![Image](https://github.com/user-attachments/assets/d67c8094-843c-4525-a279-97ef41de2366)

#### add bookmark toggle
![Image](https://github.com/user-attachments/assets/a423205c-2da1-403e-8da5-d34b93ecc4d2)

</details> 

### [Production](https://archives.iu.edu/)

<details> 
<summary> See Screenshot </summary>

![Image](https://github.com/user-attachments/assets/fd6a30fa-3678-486e-9ba4-26f916b98e39)

</details>

# Testing Instructions

1. Visit [staging](https://archives-online-staging.notch8.cloud/)
2. The user should not have the ability to see or use the bookmark or history features, that comes with arclight.

# Notes

Maybe helpful: 

production [code](https://github.com/IUBLibTech/ngao)
arclight [code](https://github.com/projectblacklight/arclight)

Remove bookmarks ngao PRs: 
1. [Remove routes](https://github.com/IUBLibTech/ngao/pull/98)
2. [remove bookmark and logins](https://github.com/IUBLibTech/ngao/pull/15)
3. Going to /bookmarks or /search_history should render an error

**Comment by kirkkwang** [comment]
✅ No more bookmark/history

![Image](https://github.com/user-attachments/assets/74e9145f-aff3-4f78-a944-25068c39954b)


Routes are gone too
![Image](https://github.com/user-attachments/assets/2858b451-b0cb-4f9b-9e4a-884ece7f0983)
![Image](https://github.com/user-attachments/assets/1600ff3e-db97-4f65-8c9e-1243b2db2629)

**Comment by brijmcla** [comment]
Acceptance criteria has been met
