### ISSUE TITLE
:gift: Add Collection Number in Search

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/archives_online#23]
# Summary

When searching for a collection, the collection number should be present in the results.

TODO: Get clarification from client. What is the "collection number"?

# Acceptance Criteria

- [X] Archives online matches parity with production; the collection number should be present in the search results.
- [X] Collection ID should be viewable in search results next to the collection name

# Screenshots or Video

## [STAGING](https://archives-online-staging.notch8.cloud/catalog?search_field=all_fields&q=general)

<details> 
<summary> See Screenshot </summary> 

![Image](https://github.com/user-attachments/assets/df1f6eb4-26d9-450c-962a-83f30578f72e)

</details>

## [PRODUCTION](https://archives.iu.edu/catalog?f%5Bcollection_sim%5D%5B%5D=Solley+mss.%2C+1888-2006&group=true&q=test&search_field=all_fields)

<details> 
<summary> See Screenshot </summary> 

![Image](https://github.com/user-attachments/assets/71f9ef9d-1744-4217-966c-285e53816932)

</details>

# Testing Instructions

1. Do a search
2. Confirm that you see the Collection ID: in the results when grouped by collection

# Notes

TODO: 
**Q: Get clarification from the client. Is the "collection number" the same as "Collection ID?"** [ref](https://assaydepot.slack.com/archives/C07GJGVQS2V/p1724368494658829)

Maybe helpful:
production [code](https://github.com/IUBLibTech/ngao)

https://github.com/IUBLibTech/ngao/pull/234

**Comment by brijmcla** [comment]
To clarify, "Collection ID" is the same as "Unit ID." It may look confusing because the dropdown menu includes "Unit ID" but the identifier in the finding aid search results view is "Collection ID." They're one in the same--we have an open ticket to change the  search bag dropdown menu from "Unit ID" to "Collection ID."

**Comment by kirkkwang** [comment]
✅ I see the Collection ID now

![Image](https://github.com/user-attachments/assets/885e1ac0-0653-4dd7-9407-6f955c8111a4)
