### ISSUE TITLE
:gift: Grouped Results by Collection

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/archives_online#24]
# Summary

When you perform a search in production, "Grouped by collection" is selected by default. Archives online should behave the same way.

# Acceptance Criteria

- [x] Archives online matches feature parity with production. It should Group by collection on default when a user performs a search. 

# Screenshots or Video

![image](https://github.com/user-attachments/assets/4c028b41-0b36-4d88-b736-2ebadde1ad50)

# Testing Instructions

1. Visit [staging](https://archives-online-staging.notch8.cloud/catalog?group=true&q=general&search_field=all_fields)
2. Search for a collection
3. By default, the results should be "Grouped by collection"
4. a user should still be able to toggle to All Results, if desired.

# Notes
The name of [this file](https://github.com/IUBLibTech/ngao/blob/39bf1ce8b73f9c0f0f2c96153716f00520c6c9f3/app/views/catalog/_arclight_index_group_document_default.html.erb) [(app/views/catalog/_arclight_index_group_document_default.html.erb)](https://github.com/IUBLibTech/ngao/blob/39bf1ce8b73f9c0f0f2c96153716f00520c6c9f3/app/views/catalog/_arclight_index_group_document_default.html.erb) smells like a clue for how this was originally implemented.

original implementation? https://github.com/IUBLibTech/ngao/commit/522789849116887b481089f3f04536f79912d249

**Comment by brijmcla** [comment]
The declared acceptance criteria looks good to me.

**Comment by kirkkwang** [comment]
✅ Passes QA

![Image](https://github.com/user-attachments/assets/5674dbb1-1794-48a2-b214-28f8c49a31da)

**Comment by brijmcla** [comment]
Acceptance criteria has been met

**Comment by sjproctor** [comment]
Looks good to me!
