### ISSUE TITLE
:gift: Apply styling

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/archives_online#26]
# Summary

Apply IU branding to the archives_online instance. [Style Guide](https://www.iu.edu/brand/index.html)

Per [Bri](https://assaydepot.slack.com/archives/C07GJGVQS2V/p1724348711729419?thread_ts=1724272175.545429&cid=C07GJGVQS2V): 

"I think the only UI change will be the side-by-side finding aid view baked into Arclight 1.x. Otherwise, all branding and elements should stay the same. However, I'd like confirmation from [@Julie Hardesty](https://assaydepot.slack.com/team/U07G8C2KQQL), [@Randall Floyd](https://assaydepot.slack.com/team/U07G5PZ5W1H), and/or [@Jim](https://assaydepot.slack.com/team/U07GUM39K0Q)."

**UPDATE**: To clarify, side by side is a new feature from arclight out of the box. Just make the colors IU specific. No mock up is required.

# Acceptance Criteria

- [ ] archives_online's styling should match what is seen in [production](https://archives.iu.edu/repositories)

# Screenshots or Video

## BEFORE

[STAGING](https://archives-online-staging.notch8.cloud/)

![Image](https://github.com/user-attachments/assets/6a67d31d-251d-4472-b138-1f05e48fc06d)

# Testing Instructions

Visit our [staging site](https://archives-online-staging.notch8.cloud/). The styling and UI elements should match parity with what is seen in production.

# Notes

**Questions:** 
How did they originally implement styling? Is it dynamic? 
- whatever the answer is, the client says to implement it the same way

[PR](https://github.com/IUBLibTech/ngao/pull/17) that adds IU branded header/footer

**Comment by ShanaLMoore** [comment]
Accessibility [results](https://assaydepot.slack.com/archives/C07GJGVQS2V/p1724686190057819) from the basic site (before styling)



![Image](https://github.com/user-attachments/assets/13a4b2bf-e0a8-4f95-9952-5a597e6b04de)

**Comment by ShanaLMoore** [comment]
Bri - What does dynamic styling mean?

**Comment by brijmcla** [comment]
I think the search results pagination is still following our old styling instead of the new Rivet styling: https://rivet.iu.edu/components/pagination/?example=large-dataset-pagination#accessibility

Large dataset pagination is the best option for this instance.

**Comment by brijmcla** [comment]
Please change footer to the follow River footer: https://rivet.iu.edu/components/footer/?example=footer-with-resource-links
The resource links will be the About, Contribute to AO, and Harmful Language Statement.

**Comment by brijmcla** [comment]
We would like to keep the pagination as it is on the staging site rather than using the Rivet pagination style. No changes are necessary.

**Comment by brijmcla** [comment]
Acceptance criteria has been met
