### ISSUE TITLE
🎁 Add Footer

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/archives_online#33]
# Summary

Ask clients for clarification, to fill in the details of this ticket.

# Acceptance Criteria

- [ ] The site's privacy policy and/or related links are available in the footer. 
- [ ] This work passes an accessibility review
  - [ ] After this gets deployed to staging, ping Julie and Bri. They will use their plugin to run an audit on the page, to let us know if it passes review. 

# Screenshots or Video

## Privacy Policy

<details>

![image](https://github.com/user-attachments/assets/89c0f22e-cc72-4a69-b832-e9c7ce36d8ca)

</details>

# Testing Instructions

# Notes

**Questions:** 

[PR](https://github.com/IUBLibTech/ngao/pull/17) that added the privacy policy to the ngao/production code

[PR](https://github.com/IUBLibTech/ngao/pull/14) for campus cards and privacy policy

**Comment by jillpe** [comment]
covered in #20
