### ISSUE TITLE
🧹 Final Accessibility Review

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/archives_online#38]
# Summary

This task is for Julie or Bri to do a final accessibility Audit, after most of our work is compelte. 

# Acceptance Criteria

- [ ] Our completed work passes the accessibility review
- [ ] If not, separate tickets are created to work on the issues

**Comment by brijmcla** [comment]
I'm still getting interactive element sizing errors with breadcrumbs in search results. It looks like the error is only occurring when the text wraps. Here is a video where I demonstrate the error skipping one finding aid's breadcrumbs until I resize the window. 

https://github.com/user-attachments/assets/fef21e1a-bbcc-4579-870f-3511f2a4c8ad

**Comment by brijmcla** [comment]
In an empty search, I see empty container elements in the white space between finding aids. See screenshot below. 
![empty container element](https://github.com/user-attachments/assets/743d19a9-23b8-46e5-b7bc-4285b9719eec)

**Comment by brijmcla** [comment]
The "Apply" button after the range of the search facet has the error "hidden element has focusable content." See screenshot below.
![focusable content](https://github.com/user-attachments/assets/faf59cfc-bf30-4767-91b6-67dfbe000b8a)

**Comment by brijmcla** [comment]
All text links must be underlined. Please see screenshots below of our production instance for example.
![underlined links](https://github.com/user-attachments/assets/766ee5ac-9735-4544-b596-bc5bb3a35533)
![underlined links 2](https://github.com/user-attachments/assets/b612071e-0829-490e-9132-20fd6a28305e)

**Comment by brijmcla** [comment]
This one is puzzling. I'm seeing another interactive element spacing issue, but the location doesn't make sense. The text the error points to is in the breadcrumbs, but the location is up in the search bar. Please see screenshot below.


![Image](https://github.com/user-attachments/assets/ae8c0114-73b1-4e72-a4e6-4fa0070c829d)

**Comment by kirkkwang** [comment]
Spin off tickets:
#66 
#67 
#68 
#69 
#70
