### ISSUE TITLE
item level unitids is not displaying

### ISSUE THREAD

**Issue by brijmcla** [scientist-softserv/archives_online#47]
# Story
`unitid` is not displaying at the item level. 
Here is the EAD for the item in the following example: 
```
 <c03 id="aspace_VAD4090-00094" level="item">
            <did>
              <unittitle>Choices</unittitle>
              <unitid>COL 5 VH 1</unitid>
              <unitid audience="internal" identifier="COL 5 VH 1" type="shelf">COL 5 VH 1</unitid>
              <unitid audience="internal" identifier="1" type="collector">1</unitid>
              <origination label="Creator"><persname source="ingest">Sampson,
                Sheldon</persname></origination>
              <unitdate datechar="creation" normal="1993/1993">1993</unitdate>
              <physdesc id="aspace_f442258bcd8b6f91bff824ed586b90b6" label="Physical Description">1
                videocassette (VHS)</physdesc>
            </did>
            <originalsloc id="aspace_cbf65fde88732d9455afab810a03f9db">
              <head>Format of original version</head>
              <p>1 film reel (28 minutes) : sound, color ; 16 mm</p>
            </originalsloc>
          </c03>
```
In the staging environment, you can see the collection level `unitid` if you click the More Info button on the top left corner of the screen (see screenshot). 
# Acceptance Criteria

- [x] all `unitid` is displaying at item level

# Screenshots / Video
Production instance:
![unitids_arclight_prod](https://github.com/user-attachments/assets/24e8c759-f7da-43d5-bebd-ac42ee78bbc6)
Staging instance:
![no_unit_ids](https://github.com/user-attachments/assets/92675bc5-d1c2-40d3-bfa8-0ac9d8b1191c)

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-navigate to "[Choices, 1993](https://archives-online-staging.notch8.cloud/catalog/VAD4090_aspace_VAD4090-00094)" in "[Mary Perry Smith Black Filmmakers Hall of Fame Archives collection, Series 5. Sidney Poitier Fellowship Competition, 1985-1993, bulk 1992-1993](https://archives-online-staging.notch8.cloud/catalog/VAD4090)" finding aid and check if `unitid `COL 5 VH 1 and 1 are displaying. Ideally there is a "Component Identifier" field that the `unitid `are within, but that might be a separate issue.

# Notes

**Comment by kirkkwang** [comment]
✅ Passes QA on staging
NOTE: the component identifier appears in an area that is different than the more info area though

![Image](https://github.com/user-attachments/assets/901a9ce2-1f46-43ab-965b-31ee56ad1c88)

**Comment by brijmcla** [comment]
Acceptance criteria has been met.
