### ISSUE TITLE
bibliography note is not displaying

### ISSUE THREAD

**Issue by brijmcla** [scientist-softserv/archives_online#48]
# Story
All note types display at the item and collection level are displaying with the exception of `bibliography `notes. `bibliography` is within `archdesc `in EAD. 
```
    <bibliography id="aspace_4446a0008a571b67b4728cf714a0657d">
      <head>Bibliography</head>
      <p>bibliography text</p>
    </bibliography>
```
# Acceptance Criteria

- [x] `bibliography `displays at collection level
- [x] `bibliography `displays at item level

# Screenshots / Video
I don't have a 1:1 example screenshot, but here is an example of where the bibliography displays in our production instance 
![Uploading bibliography.jpg…]()

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-Navigate to finding aid and check if a bibliography note is displaying
-Navigate to item and check if a bibliography note is displaying

# Notes

**Comment by kirkkwang** [comment]
✅ Passes QA, i see the `Bibliography` on staging

![Image](https://github.com/user-attachments/assets/a597f5ee-8f6f-4c75-9227-e8cbddaf3e33)

![Image](https://github.com/user-attachments/assets/85f71fe7-9466-40c0-a458-504ce000117e)

**Comment by brijmcla** [comment]
Acceptance criteria has been met.
