### ISSUE TITLE
Year search facet with date slider is missing

### ISSUE THREAD

**Issue by brijmcla** [scientist-softserv/archives_online#53]
# Story

# Acceptance Criteria

- [x] Year search facet displays and functions
- [ ] Date slider is present within Year search facet

# Screenshots / Video
![year_facet](https://github.com/user-attachments/assets/790e7fae-3d76-4625-ba3d-840c80ae372a)
<details>
<summary></summary>
![year_facet](https://github.com/user-attachments/assets/790e7fae-3d76-4625-ba3d-840c80ae372a)

</details>

# Testing Instructions and Sample Files

- Click the search button on the [homepage](https://archives-online-staging.notch8.cloud/)
- Check if Year facet shows up on the left side of the screen
- Click the Year facet button to ensure that the date slider also shows up (⚠️ See notes)

# Notes
⚠️ The date slider does not function at the moment, there seems to be an incompatibility with Rails 7/Blacklight 8.  
See: 
- https://github.com/projectblacklight/blacklight_range_limit/issues/236

**Comment by kirkkwang** [comment]
✅ Passes QA with the caveat that the slider is not compatible with this version of Arclight

![Image](https://github.com/user-attachments/assets/4e447d41-6af5-48a3-b96b-d4f09bc40d31)

**Comment by brijmcla** [comment]
I wanted to confirm on the ticket that I agreed to exclude the date slider since it was not compatible with Arclight and wasn't a very helpful function to begin with.

**Comment by brijmcla** [comment]
Acceptance criteria has been met.
