### ISSUE TITLE
`repositories.yml` needs change to `contact_html` and `location_html`

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/archives_online#55]
# Story

In Arclight v1.4.0, the way the contacts and locations are populated changed and the current `repositories.yml` is still the old version.

# Acceptance Criteria

- [x] Contact is displayed
- [x] Location is displayed

# Screenshots / Video

## On prod:
![Image](https://github.com/user-attachments/assets/b125b07a-3367-4e10-b122-1ff9e0f4ab45)

## On staging:
![Image](https://github.com/user-attachments/assets/38165d58-ab71-4f78-8fc2-0c7fa592ebff)

# Testing Instructions and Sample Files

- Go to the index page
- Scroll down to the horizontal cards
- Confirm that the address and contact is displayed

**Comment by kirkkwang** [comment]
✅ Passes QA

![Image](https://github.com/user-attachments/assets/e0dbbac7-6cd8-49aa-8e5d-4cc684c7975e)

**Comment by brijmcla** [comment]
Acceptance criteria has been met
