### ISSUE TITLE
Gap Analysis between the current app and the new app is made and linked in this ticket

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/archives_online#8]
# Summary

Review ngao code vs archives_online. Provide a document with a recommendation for how to move forward. Include the reasons why + a break down of features what we'd need to port over. 

## Related

#1 

# Acceptance Criteria

- [ ] The client reviews our recommendations and gives an approval
- [ ] The client reviews and prioritizes the list of features to implement

# Recommendation: 

[Upgrading ngao or Continuing with archives_online.pdf](https://github.com/user-attachments/files/16696368/Upgrading.ngao.or.Continuing.with.archives_online.pdf)

**Comment by kirkkwang** [comment]
## Notes from the meeting with Rob

1.4.0 has a repository data model that requires a deploy to change
ngao has a database repository model and edit interface

Do you change the repositories frequently, is it worth it to have the repository model in the interface?

  If the answer is no, then we don't need to worry about the repository piece, we would need to download their repository data and port it into the yaml.

  If yes, we need to port the ngao repository functionality into archives_online.

Do you want to port your existing styling or implment a new style guide for the new application?


TODO:
  - figure out what they want to do with the repository
  - port EAD implementation
  - implment CAS
  - finish the UV
  - port or implement new styling

How many of these features exist in 1.4.0?
  - remove history 
    - history is still in 1.4.0, we wouuld need to modify catalog controller
  - remove bookmarks
    - bookmarks in 1.4.0, we would need to modify catalog controller
  - archivespace to arclight implementation?
    - not in 1.4.0
  - documentation for advanced search
    - unclear if it's in 1.4.0
  - port privacy policy 
    - not in 1.4.0
  - port campus feature 
    - not in 1.4.0
  - implement nightly automation process for exports
    - not in 1.4.0
  - restricting admin page to limit repositories based on access
    - not in 1.4.0
    - https://github.com/IUBLibTech/ngao/pull/45
  - ability to add links to static content?
    - not in 1.4.0
    - https://github.com/IUBLibTech/ngao/pull/53
  - additional content for homepage
    - unclear if this is in 1.4.0
  - repository listings by campus
    - unclear if this is in 1.4.0
  - adding collection number to search field
    - not in 1.4.0, need to modify the catalog controller
    - https://github.com/IUBLibTech/ngao/commit/8a48d25a8dd5c33cfb164bf545ef7288af09ed4c
  - accessibility review
    - lots of views changed especially with blacklight 8 going to view components, unclear and would need an evaluation
  - grouping results by collection
    - not in 1.4.0, this partial is completely gone, it used to override blacklight
    - https://github.com/IUBLibTech/ngao/commit/522789849116887b481089f3f04536f79912d249

**Comment by ShanaLMoore** [comment]
Meeting [notes](https://docs.google.com/document/d/1cMxOPr5fBhY6YWZdqPE2uldJQUXqmaLND1gUSLejAeM/edit#heading=h.3zeglegwljh)

## Priorities



![Image](https://github.com/user-attachments/assets/d1636cdd-5277-4494-acb1-1fde8f8d7392)
